### ISSUE TITLE
Regression: invalid decoding of repeated nullbytes 

### ISSUE THREAD

**Issue by grobie** [ideaship/ttar#1]
https://github.com/ideaship/ttar/commit/689319f38557e7676709d945fb8ccad9cc549478 added a regression where a file with repeated nul bytes doesn't get properly decoded (a sequence `NULLBYTENULLBYTENULLBYTE` should result in `\0\0\0`).

**Comment by ideaship** [comment]
@grobie Thanks for reporting this bug. It should be resolved on all supported platforms.
